import PDFDocument from "pdfkit";
import archiver from "archiver";
import slugify from "slugify";
import { Request, Response } from "express";
import { format } from "date-fns";
import Note from "../models/noteModel";

export const exportNotesAsZip = async (req: Request, res: Response) => {
  try {
    const userId = req.userId;

    const notes = await Note.find({ userId });

    if (notes.length === 0) {
      res.status(404).json({ message: "No notes found to export!" });
      return;
    }

    res.setHeader("Content-Type", "application/zip");
    res.setHeader(
      "Content-Disposition",
      `attachment; filename="notes-export.zip"`
    );

    const archive = archiver("zip", { zlib: { level: 9 } });
    archive.pipe(res);

    const pdfPromises = notes.map((note) => {
      return new Promise<void>((resolve) => {
        const doc = new PDFDocument();
        const chunks: Buffer[] = [];

        doc.on("data", (chunk) => chunks.push(chunk));
        doc.on("end", () => {
          const pdfBuffer = Buffer.concat(chunks);
          const safeFileName =
            slugify(note.title || "untitled", { lower: true, strict: true }) +
            ".pdf";
          archive.append(pdfBuffer, { name: safeFileName });
          resolve();
        });

        // PDF content
        doc.fontSize(20).text(note.title, { underline: true });
        doc.moveDown();
        doc
          .fontSize(10)
          .fillColor("gray")
          .text(`Created: ${format(note.createdAt, "PPPpp")}`);
        if (note.tags.length > 0) {
          doc
            .moveDown()
            .fillColor("blue")
            .text(`Tags: ${note.tags.join(", ")}`);
        }
        doc.moveDown().fillColor("black").fontSize(14).text(note.content);
        doc.moveDown(4);
        doc
          .fontSize(10)
          .fillColor("gray")
          .text("Generated by SkillSail Notes", { align: "center" });

        doc.end();
      });
    });

    await Promise.all(pdfPromises);

    // Finalize the archive after all PDFs are added
    archive.finalize();
  } catch (error) {
    res
      .status(500)
      .json({ message: "Server error while exporting notes as zip" });
  }
};
